base/urls.py
from django.urls import path
from .views import CurrentUserTasks, IndexView, TaskChangeAPI, TaskDetailView, TaskCreateView, TaskEditUsingMixin, TaskListAPI, TaskListUsingMixin, TaskUpdateView, TaskDeleteView, CustomLoginView, CustomRegisterView, TaskChangeAPI, TimeView, api_overview
from django.contrib.auth.views import LogoutView

app_name = 'base'

urlpatterns = [
    path('times/', TimeView.as_view(), name='times'),
    path('login', CustomLoginView.as_view(), name='login'),
    path('register', CustomRegisterView.as_view(), name='register'),
    path('logout', LogoutView.as_view(next_page='base:login'), name='logout'),
    path('', IndexView.as_view(), name='index'),
    path('task/<int:pk>', TaskDetailView.as_view(), name='task'),
    path('task-create',
         TaskCreateView.as_view(), name='task-create'),
    path('task-update/<int:pk>', TaskUpdateView.as_view(), name='task-update'),
    path('task-delete/<int:pk>', TaskDeleteView.as_view(), name='task-delete'),


    path('api/', api_overview, name="api_overview"),

    path('api/mytasks', CurrentUserTasks.as_view(), name="my-tasks"),

    path('api/tasks', TaskListAPI.as_view(), name="tasks"),
    path('api/task/<int:pk>', TaskChangeAPI.as_view(), name="task-change"),

    path('api/task-list', TaskListUsingMixin.as_view(), name="task-list"),
    path('api/task-edit/<int:pk>', TaskEditUsingMixin.as_view(), name="task-edit"),
]

# urlpatterns = format_suffix_patterns(urlpatterns)

todo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls')),
    path('api/users/', include('users.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
]

base/models.py
from django.utils import timezone
from .validations import DescriptionValidator
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db.models.signals import pre_save, post_save
from rest_framework.authtoken.models import Token


class UserManager(BaseUserManager):
    def create_user(self, email, name, city=None, age=None, password=None):
        if not email:
            raise ValueError('Email can\'t be null')
        if not name:
            raise ValueError('Name can\'t be null')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
            city=city,
            age=age,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password, city=None, age=None):
        user = self.create_user(
            email=self.normalize_email(email),
            name=name,
            city=city,
            age=age,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    name = models.CharField(max_length=50)
    age = models.IntegerField(default=0, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    country = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=False)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    users = UserManager()

    def __str__(self) -> str:
        return self.name

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    def save(self, *args, **kwargs):
        self.country = 'Pakistan'
        self.created = timezone.now()
        return super(User, self).save(*args, **kwargs)


class TaskQuerySet(models.QuerySet):
    def sorted(self, param):
        return self.order_by(f'{param}')


class TaskManager(models.Manager):
    def get_queryset(self):
        return TaskQuerySet(model=self.model, using=self._db)


class Task(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, default=None)
    title = models.CharField(max_length=200)
    description = models.TextField(validators=[DescriptionValidator])
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField()

    REQUIRED_FIELDS = ['title', 'description']

    tasks = TaskManager()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.updated = timezone.now()
        return super(Task, self).save(*args, **kwargs)

    class Meta:
        ordering = ['complete']

class Time(models.Model):
    time = models.DateTimeField(null=True, blank=True)
    timezone = models.CharField(max_length=20, default='PST')
    REQUIRED_FIELDS = ['time']

    def __str__(self):
        return self.time

    class Meta:
        ordering = ['id']


def task_pre_save(sender, instance, *args, **kwargs):
    if not instance.title.istitle():
        instance.title = instance.title.title()
        instance.save()

    if instance.description and not instance.description[0].isupper():
        instance.description = instance.description.capitalize()
        instance.save()
pre_save.connect(task_pre_save, sender=Task)


def user_post_save(sender, instance, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)
post_save.connect(user_post_save, sender=User)

base/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django import forms
from .models import User


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=50, help_text='Please add a valid email address')

    class Meta:
        model = User
        fields = ['email', 'name', 'city', 'age', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            user = User.users.get(email=email)
        except Exception as e:
            return email
        raise forms.ValidationError(f'Email {email} already in use.')

base/views.py
from datetime import datetime
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.exceptions import ValidationError

from django.contrib.auth import login, authenticate
from django.http import Http404

from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework import mixins
from rest_framework import generics
from rest_framework import status

from django.shortcuts import redirect
from django.urls import reverse_lazy

from .forms import UserRegistrationForm
from .filters import TaskFilter
from .models import Task, Time
from .serializers import TaskSerializer
from .mixins import CurrentUserLookupMixin


class TimeView(ListView):
    model = Time
    fields = "__all__"
    context_object_name = 'times_list'
    template_name = 'base/times.html'



@api_view(['GET'])
def api_overview(request):
    api_urls = {
        'Add Task / Display all Tasks': 'api/tasks',
        'Task Detail/Update/Delete': 'api/task/<int:pk>',
        '(Using Mixin) Add Task / Display all Tasks': 'api/task-list',
        '(Using Mixin) Task Detail / Update / Delete': 'api/task-edit/<int:pk>',
    }

    return Response(api_urls)


class TaskListAPI(APIView):

    def get(self, request):
        tasks = Task.tasks.all()
        serializer = TaskSerializer(tasks, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = TaskSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class TaskChangeAPI(APIView):

    def get_object(self, pk):
        try:
            return Task.tasks.get(id=pk)
        except Task.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        task = self.get_object(pk)
        serializer = TaskSerializer(task)
        return Response(serializer.data)

    def put(self, request, pk):
        task = self.get_object(pk)
        serializer = TaskSerializer(task, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        task = self.get_object(pk)
        task.delete()
        return Response('Task Deleted')

    def perform_destroy(self, instance):
        if(instance.created == False):
            raise ValidationError('Task should be completed first.')
        instance.destroy()


class TaskListUsingMixin(mixins.ListModelMixin, mixins.CreateModelMixin, generics.GenericAPIView):
    queryset = Task.tasks.all()
    serializer_class = TaskSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class CurrentUserTasks(CurrentUserLookupMixin, generics.GenericAPIView):
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = Task.tasks.all()
    serializer_class = TaskSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


class TaskEditUsingMixin(mixins.RetrieveModelMixin, mixins.UpdateModelMixin, mixins.DestroyModelMixin, generics.GenericAPIView):
    queryset = Task.tasks.all()
    serializer_class = TaskSerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)


class TasksView(generics.ListCreateAPIView):
    queryset = Task.tasks.all()
    serializer_class = TaskSerializer


class TaskEdit(generics.RetrieveUpdateDestroyAPIView):
    queryset = Task.tasks.all()
    serializer_class = TaskSerializer


class CustomLoginView(LoginView):
    fields = '__all__'
    template_name = 'base/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('base:index')


class CustomRegisterView(FormView):
    template_name = 'base/register.html'
    form_class = UserRegistrationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('base:index')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            email = form.cleaned_data.get('email').lower()
            raw_password = form.cleaned_data.get('password1')
            authenticate(email=email, password=raw_password)
            login(self.request, user)
        return super(CustomRegisterView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('base:index',  *args, **kwargs)
        return super(CustomRegisterView, self).get(request, *args, **kwargs)


class IndexView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'base/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tasks = context['tasks'].filter(user=self.request.user)
        context['tasks'] = tasks.sorted('complete')
        myFilter = TaskFilter(self.request.GET, queryset=tasks)

        # search_input = self.request.GET.get('search-area') or ''
        # if(search_input):
        #     context['tasks'] = context['tasks'].filter(
        #         title__startswith=search_input)

        # context['search_area'] = search_input
        context['tasks'] = myFilter.qs
        context['myFilter'] = myFilter

        return context


class TaskDetailView(DetailView):
    template_name = 'base/task.html'
    queryset = Task.tasks.all()

    def get_object(self):
        task = super().get_object()
        task.created = datetime.now()
        task.save()
        return task


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('base:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreateView, self).form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('base:index')


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('base:index')

base/templates/base/index.html
{% extends 'base/main.html'%}
{% load tz %}

{% block style %}
input[type='text']{
  max-width: 120px
}
{% endblock %}
{% block content %}
<h1 class="header-bar">TODO-APP</h1>
<div class="card-body">
  <div class='d-flex flex-row justify-content-between mb-3'>
    <p><a href="{% url 'base:task-create' %}" class="text-start m-4">+ Add Task</a> </p>
    {% if request.user.is_authenticated %}
    <p class="text-end">
      Welcome {{request.user}} - <a href="{% url 'base:logout' %}">Logout</a>
    </p>
    {% else %}
    <p><a href="{% url 'base:login' %}">Login</a></p>
    {% endif %}
  </div>
  

  

  {% comment %}
  <input
    type="text"
    name="search-area"
    value="{{search_area}}"
    style="width: 80%"
  />
  {% endcomment %}
  <form method="get" style="width: 90%;" class="mx-auto my-3">
    {{myFilter.form}}
    <input type="submit" value="Submit" style="width: 18%" />
  </form>

  {% if not tasks %}
  <p style='margin-left: 30px; font-size: 24px'><strong>Nothing in ToDo List</strong></p>
  {% else %}
  <table class="mt-3" style="width: 90%; margin: auto">
    <tr>
      <th style="width: 40%">
        Title
        <hr />
      </th>
      <th style="width: 40%">
        Created
        <hr />
      </th>
      <th colspan="2" class="text-center" style="width: 20%">
        Actions
        <hr />
      </th>
    </tr>
    {% for task in tasks %}
    <tr>
      <td>
        {% if task.complete %}
        <s>{{task}}</s>
        {% else %} {{task}} {% endif %}
      </td>
      <td style='font-size: 14px'>
        {{task.created}}</td>
      <td class="text-center"><a href="/task-update/{{task.id}}">Edit</a></td>
      <td class="text-center"><a href="/task-delete/{{task.id}}">Delete</a></td>
    </tr>
    {% endfor %}
  </table>

  {% endif %}
</div>
{% endblock content %}

base/templates/base/login.html
{% extends 'base/main.html'%} {% block content %}
<h1 class="header-bar">Login</h1>

<div class="card-body">
  <form method="post">
    {% csrf_token %}
    <div class="form-outline mb-4">
      <label class="form-label" for="form1Example13"
        >{{form.username.label}}</label
      >
      <input type="text" id="username" name="username" class="form-control" />
    </div>

    <!-- Password input -->
    <div class="form-outline mb-4">
      <label class="form-label" for="form1Example23"
        >{{form.password.label}}</label
      >
      <input
        type="password"
        id="password"
        name="password"
        class="form-control"
      />
    </div>

    {% for error in form.non_field_errors %}
      <p style='color: red'>{{error}}</p>
    {% endfor %}

    
    <input type="submit" name="submit" />
  </form>

  <p class="text-center mt-5">
    Don't have an account yet? <a href="{% url 'base:register' %}">Register</a>
  </p>
</div>

{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    <title>Todo List App</title>
    <style>
      {% block style %}
      {% endblock %}
      body {
        background-color: #f0f0f0;
        padding-top: 100px;
      }
      .container {
        background-color: #fff;
        max-width: 600px;
        padding: 0;
      }
      .header-bar {
        background-color: rgb(247, 156, 0);
        text-align: center;
        padding: 20px 0;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
      }
      input[type='submit'] {
        background-color: #0d6efd;
        padding: 5px 15px;
        border: none;
        border-radius: 5px;
        color: white;
      }
      a {
        text-decoration: none;
      }
    </style>
  </head>
  <body>
    <div class="container rounded m-auto">
      <div class="card border-0 rounded" style="width: 100%">
        {% block content %} {% endblock content %}
      </div>
    </div>
  </body>
</html>

base/templates/base/register.html
{% extends 'base/main.html'%} 
{% block style %}
body{
  padding-top: 10px !important
}
{%endblock%}
{% block content %}

<h1 class="header-bar">Register</h1>

<div class="card-body">
  <form method="post">
    {% csrf_token %}

    <div class="form-outline mb-4">
      <label class="form-label" for="email"
        >{{form.email.label}}*</label
      >
      <input type="email" id="email" name="email" class="form-control" />
      {% for error in form.email.errors %}
        <p style="color: red">{{error}}</p>
      {% endfor %}
    </div>

    <div class="form-outline mb-4">
      <label class="form-label" for="name"
        >{{form.name.label}}*</label
      >
      <input type="text" id="name" name="name" class="form-control" />
      {% for error in form.name.errors %}
        <p style="color: red">{{error}}</p>
      {% endfor %}
    </div>

    <div class="form-outline mb-4">
      <label class="form-label" for="age"
        >{{form.age.label}}</label
      >
      <input type="text" id="age" name="age" class="form-control" />
      {% for error in form.age.errors %}
        <p style="color: red">{{error}}</p>
      {% endfor %}
    </div>

    <div class="form-outline mb-4">
      <label class="form-label" for="city"
        >{{form.city.label}}</label
      >
      <input type="text" id="city" name="city" class="form-control" />
      {% for error in form.city.errors %}
        <p style="color: red">{{error}}</p>
      {% endfor %}
    </div>

    <!-- Password input -->
    <div class="form-outline mb-4">
      <label class="form-label" for="password1"
        >{{form.password1.label}}*</label
      >
      <input
        type="password"
        id="password1"
        name="password1"
        class="form-control"
      />
    </div>

    <!-- Confirm Password input -->
    <div class="form-outline mb-4">
      <label class="form-label" for="password2"
        >{{form.password2.label|title}}*</label>
      <input
        type="password"
        id="password2"
        name="password2"
        class="form-control"
      />
      {% for error in form.password2.errors %}
        <p style="color: red">{{error}}</p>
      {% endfor %}
    </div>
    

    <input type="submit" name="submit" />
  </form>
  <p class="text-center mt-5">
    Already have an account? <a href="{% url 'base:login' %}">Login</a>
  </p>
</div>
{% endblock content %}

base/templates/base/task.html
<h1>Task: {{task}}</h1>
<p>{{task.created}}</p>

base/templates/base/task_confirm_delete.html
{% extends 'base/main.html'%} {% block content %}
<h1 class="header-bar">Delete Task</h1>
<div class="card-body">
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete <strong>{{task.title}}</strong></p>
    <input type="submit" name="submit" value="Yes" />
    <a href="{% url 'base:index' %}" class="btn">No</a>
  </form>
</div>
{% endblock content %}

base/templates/base/task_form.html
{% extends 'base/main.html'%} {% block content %}
<h1 class="header-bar">Add Task</h1>
<div class="card-body">
  <a href="{% url 'base:index' %}" style="text-decoration: underline"
    >Go Back</a
  >
  <form method="post" class="mt-3">
    {% csrf_token %} 
    {{ form.as_p }}
    {% comment %} <div class="form-outline mb-4">
      <label class="form-label" for="title">{{form.title.label}}</label>
      <input
        type="text"
        id="title"
        name="title"
        class="form-control"
        value="{% if form.title.value %}{{ form.title.value }}{% endif %}"
      />
      {% for error in form.title.errors %}
        <p style='color: red'>{{error}}</p>
      {% endfor %}
    </div>
    <div class="mb-3">
      <label for="description" class="form-label"
        >{{form.description.label}}</label
      >
      <textarea
        class="form-control"
        name="description"
        id="description"
        rows="3"
      >
      {% if form.description.value %}{{ form.description.value }}{% endif %}</textarea
      >
      {% for error in form.description.errors %}
        <p style="color: red">{{error}}</p>
      {% endfor %}
    </div>
    <div class="form-check">
      <input
        class="form-check-input"
        type="checkbox"
        id="complete"
        name="complete"
        {%if form.complete.value %}
        checked
        {%endif%}
      />
      <label class="form-check-label" for="complete">
        {{form.complete.label}}</label
      >
    </div> {% endcomment %}
    <input type="submit" name="submit" class="mt-3" />
  </form>
</div>

{% endblock content %}

base/templates/base/times.html
{% extends 'base/main.html'%} {% load tz %} {% block content %}

<table class="mt-3" style="width: 90%; margin: auto">
  <tr>
    <th>
      ID
      <hr />
    </th>
    <th>
      Time
      <hr />
    </th>
    <th>
      Timezone
      <hr />
    </th>
  </tr>
  {% for row in times_list %}
  <tr>
    <td>{{row.id}}</td>
    <td>
      {% if row.timezone == 'PST' %} 
        {% timezone "US/Pacific" %}{{row.time}}{% endtimezone %} 
      {% else %} 
          {% timezone "UTC" %}{{row.time}}{% endtimezone %} 
      {% endif %}
    </td>
    <td style="font-size: 14px">{{row.timezone}}</td>
  </tr>
  {% endfor %}
</table>
{% endblock content %}